### ISSUE TITLE
2. Là một học sinh đã đăng nhập, tôi muốn có thể lưu lại và xem lại bài làm của mình mỗi khi làm xong bài, để có thể xem điểm của bản thân.

### ISSUE THREAD

**Issue by niits** [niits/INT2208-7-2019#2]

**Comment by niits** [comment]
- [x] Làm quen với Angular.
- [x] Làm quen với Express.
- [x] Học sử dụng mySQL và package mysql của Node.js để tạo cơ sở dữ liệu.
- [x] Thiết kế cơ sở dữ liệu sử dụng cùng với phần mềm.

**Comment by namtp12** [comment]
- [ ] Tìm hiểu karma, jasmine, angular unit testing
- [ ] Tìm hiểu mô hình MVC trong Angular
- [ ] Tìm hiểu JS Linter

- [x] Làm quen với Angular
- [x] Làm quen với Express.
- [x] Học sử dụng mySQL và package mysql của Node.js để tạo cơ sở dữ liệu.
- [x] Thiết kế cơ sở dữ liệu sử dụng cùng với phần mềm.
- [x] Thiết kế kiểu dữ liệu (model) câu hỏi

- [ ] Cắt file html sang Angular
- [ ] Thiết kế cơ sở dữ liệu lưu kết quả làm bài của người dùng
- [ ] Tạo form đăng nhập
  - [x] Thiết kế kiểu dữ liệu (model) người dùng
  - [x] Thiết kế giao diện người dùng
  - [ ] Thiết kế bộ kiểm thử, dựa trên kỹ thuật kiểm thử giá trị biên
  - [ ] Kiểm tra dữ liệu đầu vào (form validator)
  - [ ] Thiết kế mẫu (pattern)
  - [ ] Phân tích coupling và cohesive
  - [ ] Tạo chức năng lưu kết quả bài làm
  - [ ] Tạo chức năng bảo vệ router cho trang home
  - [ ] Kiểm thử tay: kiểm tra chức năng bảo vệ router
  - [x] Tạo chức năng trao đổi thông tin giữa client và server (http request, http response)
  - [x] Kiểm thử chức năng trao đổi thông tin giữa client và server (gửi yêu cầu từ máy khách)
  - [ ] Thiết kế bộ test
  - [ ] Kiểm tra độ bao phủ
  - [ ] Kiểm tra code smell
- [ ] Kiểm thử: lấy ý kiến đánh giá

**Comment by namtp12** [comment]
Sửa tiêu đề: là một học sinh đã đăng nhập...
